### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/m2-evaluacion-intermedia-saramarin23#1]
Really cool job @saramarin23 !!!

Here you have some tips to improve the exercise:

### JavaScript

- [x] Don't use an `tries.innerHTML` to store counter. Use a variable with `let`.
- [x] The order or if / else could be better. How?

### Advanced

- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?

### HTML

- [x] Use a `label` to define the content of the input
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use placeholder attribute instead of value one to show a field's hint
- [x] Do not use `<br />` if you can do the same with CSS.

### Steps to finish the game (for those far from the solution)

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that

- increments the counter and paints its value in the HTML
- collect the value of the HTML input and compare it with the random number
  - if they are equal, draw a 'You Win' message
  - if it's lower, draw a 'Too short' message
  - if it's higher, draw a 'Too long' message

5. Assign a listener to the button click to execute the previous function

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by migueldelmazo** [comment]
![](https://media.giphy.com/media/8RxCFgu88jUbe/giphy.gif)

**Comment by saramarin23** [comment]
Hola Miguel! Acabo de corregir cosillas... Lo que está sin marcar o bien no entiendo a qué te refieres o bien no sé cómo corregirlo.

Luego, creo que los "steps to finish the game" estaban ya hechos, y los dos primeros de los "further challenges" también.

¿Lo vemos mañana en un rato? 🙃

**Comment by migueldelmazo** [comment]
Mmmm sí, la verdad es que hay cosas mejorables en mis comentarios de esta issue. Lo he cambiado y te los explico:

- **Don't use an `tries.innerHTML` to store counter. Use a variable with let.** Esto significa que estás guardando el valor del contador directamente en el HTML y preferimos hacerlo en una variable let del JS y desde esa variable actualizar el `tries.innerHTML`. La explicación es que los valores que manejamos siempre deben estar en variables o constantes de JS. Además tú estás guardando un número en HTML, sitio que solo nos deja guardar textos, y entonces te tienes que estar preocupando de hacer la conversión.
- **The order or if / else could be better. How?** En los if / else estás repitiendo varias veces la comprobación `userNumber >= 1 && userNumber <= 100`. Es mejor comprobad lo contrario en el primer if, es decir, `if (isNaN(userNumber) || userNumber < 1 || userNumber > 100)` y si esto es verdadero mostrar un mensaje. Y si es falso en el resto de else if solo tienes que comprobar si es mayor, menor o igual que el número aleatorio. Quedaría más legible.
- **Move the feedback logic to a function an execute it on each click and Move you counter logic into a function and execute it on each click**: esto significa que tenemos dos acciones separadas e independientes que son actualizar **instructions** y actualizar **tries**. Puesto que son independientes vamos a crear funciones independientes para cada una de ellas. `guessNumber` solo tendría que llamar a esas dos funciones. El código estaría más legible. Tal y como está ahora a alguien que lea este código le puede entrar la duda de qué parte de la función `guessNumber` se está usando para una u otra cosa.
- **You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?**: aquí lo que queremos decir es que estás haciendo en varios sitios diferentes `instructions.innerHTML = 'Un mensaje';` Pues molaría meter este en una función más descriptiva que se podría llamar `updateInstructionsContent` y que la ejecutaríamos donde fuera necesario con `updateInstructionsContent('Un mensaje')`

Más dudas?

Gracias por hacer estas mejoras.

**Comment by saramarin23** [comment]
Done!
